# Generated by Django 3.2.9 on 2021-11-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211110_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdislikes',
            name='post_dislike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Disliked', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='post_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='posts.post'),
        ),
    ]
